const {fs,path,assert,execFileSync,helper,createScratch,launch,createView}=require('./support.cjs');
const dir=createScratch();
const base=JSON.parse(fs.readFileSync(path.join(dir,'plan-selection-preview.json'),'utf8'));
const planPath=path.join(dir,'selection-test-plan.json');
fs.writeFileSync(planPath,JSON.stringify(base));
execFileSync(process.execPath,[helper,'render','--plan',planPath,'--output',path.join(dir,'selection-test.html')]);
execFileSync(process.execPath,[helper,'render','--plan',planPath,'--output',path.join(dir,'plan-selection-preview.html'),'--preview']);
const errors=[];
(async()=>{
  const browser=await launch();
  try{
    const setup=options=>createView(browser,errors,dir,{file:'selection-test.html',...options});
    const select=(ui,id)=>ui.locator(`[data-step="${id}"] input[type=checkbox]`);
    const expand=(ui,id)=>ui.locator(`[data-step="${id}"] .pc-expand`);
    const actions=(ui,id)=>ui.locator(`[data-step="${id}"] .pc-more`);
    const decode=call=>JSON.parse(call.prompt.split('Change request JSON:\n')[1]);
    const {page,ui,frame}=await setup();
    assert.equal(await ui.locator('.pc-row').count(),9);
    assert.equal(await ui.locator('.pc-implement').isDisabled(),true);
    assert.equal(await ui.locator('.pc-apply').isVisible(),false);
    await select(ui,'monorepo').check();await select(ui,'api-client').check();
    assert.equal(await ui.locator('.pc-implement').textContent(),'Implement 2 steps');
    assert.equal(await ui.locator('.pc-selection-summary').textContent(),'2 selected · 7 left for later');
    assert.equal(await ui.locator('.pc-done').count(),0);
    assert.equal(await frame.evaluate(()=>window.__calls.length),0);
    await frame.evaluate(()=>window.__fail=true);
    await ui.locator('.pc-implement').click();
    assert.match(await ui.locator('.pc-status').textContent(),/preserved/);
    await frame.evaluate(()=>window.__fail=false);
    await ui.locator('.pc-implement').click();
    let calls=await frame.evaluate(()=>window.__calls),request=decode(calls[1]);
    assert.equal(request.intent,'implement');assert.deepEqual(request.selected_step_ids,['monorepo','api-client']);assert.deepEqual(request.operations,[]);
    assert.equal(decode(calls[0]).request_id,request.request_id);
    assert.ok(calls[1].prompt.includes('ONLY the selected work'));
    assert.equal(await ui.locator('.pc-done').count(),0,'Sending is not completion');
    await expand(ui,'api-client').click();
    const note=ui.getByRole('textbox',{name:'Note for: Define the shared API and TypeScript client',exact:true});
    await note.fill('Keep the public client minimal.');
    assert.equal(await ui.locator('.pc-apply').isVisible(),true);
    let saved=await frame.evaluate(()=>window.__savedState);
    assert.equal(saved.modelContent.operations[0].type,'add_comment');
    await frame.evaluate(state=>window.dispatchEvent(new CustomEvent('openai:set_globals',{detail:{globals:{widgetState:state}}})),{...saved,modelContent:{...saved.modelContent,operations:[],selected_step_ids:[]}});
    assert.equal(await note.inputValue(),'Keep the public client minimal.','Late host state must not erase typing');
    assert.equal(await select(ui,'api-client').isChecked(),true);
    const restored=await setup({saved});
    assert.equal(await restored.ui.getByRole('textbox',{name:'Note for: Define the shared API and TypeScript client',exact:true}).inputValue(),'Keep the public client minimal.');
    assert.equal(await select(restored.ui,'api-client').isChecked(),true);
    await ui.locator('.pc-apply').click();
    calls=await frame.evaluate(()=>window.__calls);const edit=decode(calls.at(-1));
    assert.equal(edit.intent,'edit');assert.equal(edit.selected_step_ids,undefined);assert.equal(edit.operations.length,1);
    assert.ok(calls.at(-1).prompt.includes('does not start implementation'));
    await actions(ui,'monorepo').click();await ui.getByRole('button',{name:'Remove planned step',exact:true}).click();
    assert.equal(await ui.locator('.pc-row').count(),8);assert.equal(await ui.locator('.pc-implement').textContent(),'Implement 1 step');
    await ui.getByRole('button',{name:'Undo',exact:true}).click();
    assert.equal(await select(ui,'monorepo').isChecked(),true);assert.equal(await ui.locator('.pc-row').count(),9);
    await actions(ui,'monorepo').click();await page.keyboard.press('Escape');
    assert.equal(await ui.locator('.pc-menu').count(),0);
    await actions(ui,'history').click();await ui.getByRole('button',{name:'Remove planned step',exact:true}).click();
    await ui.getByRole('button',{name:'Add step',exact:true}).click();
    await ui.getByRole('textbox',{name:'Step title',exact:true}).fill('Document the chosen scope');
    await ui.getByRole('textbox',{name:'Step title',exact:true}).press('Enter');
    const newStep=ui.locator('.pc-row').last();await newStep.getByRole('checkbox').check();
    await actions(ui,'export').click();await ui.getByRole('button',{name:'Mark as done',exact:true}).click();
    assert.equal(await ui.locator('[data-step="export"] input').count(),0);
    assert.equal(await ui.getByText('Marked done by you',{exact:true}).count(),1);
    await ui.locator('.pc-implement').click();calls=await frame.evaluate(()=>window.__calls);request=decode(calls.at(-1));
    assert.equal(request.selected_step_ids.length,3);assert.equal(request.operations.length,4);
    assert.deepEqual(request.selected_step_ids.slice(0,2),['monorepo','api-client']);
    assert.notEqual(request.request_id,decode(calls[1]).request_id);
    assert.ok(Buffer.byteLength(JSON.stringify(await frame.evaluate(()=>window.__savedState)))<16384);
    const requestPath=path.join(dir,'selection-request.json');fs.writeFileSync(requestPath,JSON.stringify(request));
    const output=JSON.parse(execFileSync(process.execPath,[helper,'apply','--plan',planPath,'--request',requestPath],{encoding:'utf8'}));
    assert.equal(output.revision,2);assert.equal(output.intent,'implement');
    const canonical=JSON.parse(fs.readFileSync(planPath,'utf8'));
    assert.equal(canonical.steps.find(s=>s.id==='api-client').comments[0].text,'Keep the public client minimal.');
    assert.equal(canonical.steps.find(s=>s.id==='api-client').status,'pending');
    assert.equal(canonical.steps.find(s=>s.id==='export').completion_source,'user');
    assert.equal(canonical.steps.find(s=>s.id==='dap').status,'pending');
    const retry=JSON.parse(execFileSync(process.execPath,[helper,'apply','--plan',planPath,'--request',requestPath],{encoding:'utf8'}));assert.equal(retry.result,'already_applied');assert.deepEqual(retry.selected_step_ids,[]);
    execFileSync(process.execPath,[helper,'render','--plan',planPath,'--output',path.join(dir,'selection-refreshed.html')]);
    const fresh=await setup({file:'selection-refreshed.html',saved});assert.equal(await fresh.ui.locator('.pc-apply').isVisible(),false);assert.equal(await fresh.ui.locator('.pc-selected').count(),0);
    const preview=await setup({file:'plan-selection-preview.html'});await select(preview.ui,'monorepo').check();await preview.ui.locator('.pc-implement').click();assert.equal(await preview.frame.evaluate(()=>window.__calls.length),0);assert.match(await preview.ui.locator('.pc-status').textContent(),/No request was sent/);
    const offline=await setup();await select(offline.ui,'monorepo').check();await offline.frame.evaluate(()=>delete window.openai.sendFollowUpMessage);await offline.ui.locator('.pc-implement').click();assert.match(await offline.ui.locator('.pc-status').textContent(),/preserved/);
    const empty=await setup();for(let i=0;i<9;i++){await empty.ui.locator('.pc-more').first().click();await empty.ui.getByRole('button',{name:'Remove planned step',exact:true}).click();}assert.equal(await empty.ui.locator('.pc-row').count(),0);assert.equal(await empty.ui.locator('.pc-implement').isDisabled(),true);await empty.ui.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await empty.ui.locator('.pc-row').count(),1);
    for(const [width,theme] of [[736,'light'],[320,'light'],[736,'dark'],[320,'dark']]){
      const view=await setup({file:'plan-selection-preview.html',width,theme});await select(view.ui,'monorepo').check();await select(view.ui,'api-client').check();
      if(width===736){await expand(view.ui,'api-client').click();await view.ui.getByRole('textbox',{name:'Note for: Define the shared API and TypeScript client',exact:true}).fill('Keep the public client minimal.');}
      assert.equal(await view.frame.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`overflow ${width} ${theme}`);
      assert.ok(await view.ui.locator('.pc-more svg').count()>0,'Real host icons render');
      await view.ui.getByRole('region',{name:'Interactive task plan',exact:true}).screenshot({path:path.join(dir,`plan-selection-${width}-${theme}.png`)});
      await actions(view.ui,'validate').click();assert.equal(await view.frame.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);
      await view.page.close();
    }
    assert.deepEqual(errors,[]);
    console.log('PASS: subset selection, separate completion, inline notes, save-only vs implementation, remove/undo, menu keyboard, add step, host failure/retry, idempotent apply, restored drafts, stale state, preview isolation, offline preservation, empty plan, host styling/icons, 320px/736px light and dark layouts.');
    console.log('Host submission was simulated. No conversation messages or implementation were triggered.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
