const {fs,assert,execFileSync,spawnSync,helper,createScratch,launch,createView}=require('./support.cjs');
const dir=createScratch();
const source = dir + '/markdown-browser-test.md';
const html = dir + '/markdown-browser-test.html';
const requestPath = dir + '/markdown-browser-request.json';
const run = (...args) => JSON.parse(execFileSync(process.execPath, [helper, ...args], {encoding:'utf8'}));
const decode = call => JSON.parse(call.prompt.split('Change request JSON:\n')[1]);
const render = () => execFileSync(process.execPath, [helper,'render','--plan',source,'--output',html]);
const errors = [];

(async () => {
  execFileSync(process.execPath,[helper,'init','--plan',source,'--input',dir+'/markdown.json']);
  render();
  const browser = await launch();
  try {
    const setup=()=>createView(browser,errors,dir,{file:'markdown-browser-test.html'});
    const first = await setup();
    assert.match(await first.ui.locator('.pc-storage').textContent(), /markdown-browser-test\.md/);
    assert.equal(await first.ui.locator('.pc-implement').isDisabled(), true);
    const before = fs.readFileSync(source, 'utf8');
    const review = first.ui.locator('[data-step="review"]');
    await review.locator('.pc-expand').click();
    assert.equal(await review.locator('.pc-checks li').count(), 2);
    await review.locator('.pc-settings > summary').click();
    assert.match(await review.locator('.pc-inherited').textContent(), /Keyboard users/);
    await review.getByRole('combobox').selectOption('later');
    await review.getByRole('textbox', {name:'Note for: Review selection', exact:true}).fill('Persist this note in Markdown and PR context.');
    assert.equal(fs.readFileSync(source, 'utf8'), before, 'Unsubmitted edits are drafts');
    await first.ui.locator('.pc-apply').click();
    const call = await first.frame.evaluate(()=>window.__calls.at(-1));
    assert.ok(call.prompt.includes(source), 'Follow-up targets the Markdown source');
    const request = decode(call);
    assert.equal(request.intent, 'edit');
    assert.equal(request.selected_step_ids, undefined);
    fs.writeFileSync(requestPath, JSON.stringify(request));
    const applied = run('apply','--plan',source,'--request',requestPath);
    assert.equal(applied.revision, 2);
    const stored = fs.readFileSync(source,'utf8');
    assert.match(stored, /Persist this note in Markdown and PR context/);
    assert.match(stored, /"depends_on":\["build"\]/);
    assert.match(stored, /"run_after":"later"/);
    assert.match(fs.readFileSync(dir+'/markdown-browser-test-pr-notes.md','utf8'), /Persist this note in Markdown and PR context/);
    assert.equal(JSON.parse(fs.readFileSync(dir+'/markdown-browser-test.state.json','utf8')).execution, undefined);
    assert.equal(run('apply','--plan',source,'--request',requestPath).result,'already_applied');
    render();
    const refreshed = await setup();
    const savedReview = refreshed.ui.locator('[data-step="review"]');
    await savedReview.locator('.pc-expand').click();
    await savedReview.locator('.pc-settings > summary').click();
    assert.match(await savedReview.textContent(), /Persist this note in Markdown and PR context/);
    assert.equal(await savedReview.getByRole('combobox').inputValue(),'later');
    assert.equal(await savedReview.locator('.pc-checks li').count(), 2);
    assert.equal(await refreshed.ui.locator('.pc-apply').isVisible(),false);
    await savedReview.getByRole('textbox', {name:'Note for: Review selection', exact:true}).fill('A stale note must not overwrite the source.');
    await refreshed.ui.locator('.pc-apply').click();
    const stale = decode(await refreshed.frame.evaluate(()=>window.__calls.at(-1)));
    fs.writeFileSync(source,fs.readFileSync(source,'utf8').replace('Polish mobile interactions','Polish keyboard and mobile interactions'));
    fs.writeFileSync(requestPath,JSON.stringify(stale));
    const rejected = spawnSync(process.execPath,[helper,'apply','--plan',source,'--request',requestPath],{encoding:'utf8'});
    assert.notEqual(rejected.status,0);
    assert.match(rejected.stderr,/Stale plan/);
    assert.match(fs.readFileSync(source,'utf8'),/Polish keyboard and mobile interactions/);
    assert.doesNotMatch(fs.readFileSync(source,'utf8'),/A stale note must not overwrite/);
    assert.deepEqual(errors,[]);
    console.log('PASS: Markdown → card → note/timing edits → Markdown and PR notes → rebuilt card; scope preserved, drafts remain drafts, retries idempotent, stale card rejected after direct Markdown edit. Host callback simulated.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
